
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import java.util.Calendar;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import javax.swing.text.NumberFormatter;
import java.text.NumberFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ADMIN
 */
public class BiodataFrame extends javax.swing.JFrame {

    /**
     * Creates new form BiodataFrame
     */
    public BiodataFrame() {
        initComponents();
        
        try {
        MaskFormatter dateMask = new MaskFormatter("##/##/####");
        tgl_lahirFormattedTextField.setFormatterFactory(new DefaultFormatterFactory(dateMask));
    } catch (ParseException ex) {
        ex.printStackTrace();
    }
    
    // Format IPK
    NumberFormat format = NumberFormat.getInstance();
    format.setMinimumFractionDigits(2);
    format.setMaximumFractionDigits(2);
    NumberFormatter formatter = new NumberFormatter(format) {
        @Override
        public Object stringToValue(String text) throws ParseException {
            if (text == null || text.length() == 0)
                return null;
            double value = Double.parseDouble(text);
            if (value < 0 || value > 4)
                throw new ParseException("IPK harus antara 0.00 dan 4.00", 0);
            return value;
        }
    };
    formatter.setValueClass(Double.class);
    formatter.setMinimum(0.0);
    formatter.setMaximum(4.0);
    formatter.setAllowsInvalid(false);
    
    ipkFormattedTextField.setFormatterFactory(new DefaultFormatterFactory(formatter));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nikText = new javax.swing.JTextField();
        namaText = new javax.swing.JTextField();
        lakiRadioButton = new javax.swing.JRadioButton();
        perempuanRadioButton = new javax.swing.JRadioButton();
        bacaCheckBox = new javax.swing.JCheckBox();
        makanCheckBox = new javax.swing.JCheckBox();
        tidurCheckBox = new javax.swing.JCheckBox();
        daftarButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        alamatText = new javax.swing.JTextPane();
        no_telpTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tgl_lahirFormattedTextField = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        pendidikanComboBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        ipkFormattedTextField = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NIK");

        jLabel2.setText("Nama");

        jLabel4.setText("Jenis Kelamin");

        jLabel5.setText("Hobi");

        jLabel6.setText("Alamat");

        nikText.setBackground(new java.awt.Color(242, 242, 242));
        nikText.setForeground(new java.awt.Color(0, 0, 0));
        nikText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nikTextActionPerformed(evt);
            }
        });

        namaText.setBackground(new java.awt.Color(242, 242, 242));
        namaText.setForeground(new java.awt.Color(0, 0, 0));
        namaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaTextActionPerformed(evt);
            }
        });

        lakiRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        genderGroup.add(lakiRadioButton);
        lakiRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        lakiRadioButton.setSelected(true);
        lakiRadioButton.setText("Laki-laki");
        lakiRadioButton.setActionCommand("Laki-Laki");
        lakiRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakiRadioButtonActionPerformed(evt);
            }
        });

        perempuanRadioButton.setBackground(new java.awt.Color(255, 255, 255));
        genderGroup.add(perempuanRadioButton);
        perempuanRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        perempuanRadioButton.setText("Perempuan");

        bacaCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        bacaCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        bacaCheckBox.setText("Membaca");
        bacaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bacaCheckBoxActionPerformed(evt);
            }
        });

        makanCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        makanCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        makanCheckBox.setText("Makan");
        makanCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makanCheckBoxActionPerformed(evt);
            }
        });

        tidurCheckBox.setBackground(new java.awt.Color(255, 255, 255));
        tidurCheckBox.setForeground(new java.awt.Color(0, 0, 0));
        tidurCheckBox.setText("Tidur");
        tidurCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidurCheckBoxActionPerformed(evt);
            }
        });

        daftarButton.setBackground(new java.awt.Color(255, 255, 255));
        daftarButton.setForeground(new java.awt.Color(0, 0, 0));
        daftarButton.setText("DAFTAR");
        daftarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarButtonActionPerformed(evt);
            }
        });

        alamatText.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(alamatText);
        alamatText.getAccessibleContext().setAccessibleParent(alamatText);

        no_telpTextField.setBackground(new java.awt.Color(255, 255, 255));
        no_telpTextField.setForeground(new java.awt.Color(0, 0, 0));
        no_telpTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_telpTextFieldActionPerformed(evt);
            }
        });
        no_telpTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                no_telpTextFieldKeyReleased(evt);
            }
        });

        jLabel7.setText("No Telp");

        jLabel8.setText("Tanggal Lahir");

        tgl_lahirFormattedTextField.setBackground(new java.awt.Color(255, 255, 255));
        tgl_lahirFormattedTextField.setForeground(new java.awt.Color(0, 0, 0));
        tgl_lahirFormattedTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tgl_lahirFormattedTextFieldFocusLost(evt);
            }
        });
        tgl_lahirFormattedTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tgl_lahirFormattedTextFieldKeyTyped(evt);
            }
        });

        jLabel9.setText("Pendidikan");

        pendidikanComboBox.setBackground(new java.awt.Color(255, 255, 255));
        pendidikanComboBox.setForeground(new java.awt.Color(0, 0, 0));
        pendidikanComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SD", "SMP", "SMA", "D1", "D2", "D3", "D4/S1", "S2", "S3" }));
        pendidikanComboBox.setSelectedIndex(-1);
        pendidikanComboBox.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pendidikanComboBoxKeyTyped(evt);
            }
        });

        jLabel10.setText("IPK");

        ipkFormattedTextField.setBackground(new java.awt.Color(255, 255, 255));
        ipkFormattedTextField.setForeground(new java.awt.Color(0, 0, 0));
        ipkFormattedTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ipkFormattedTextFieldFocusLost(evt);
            }
        });
        ipkFormattedTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ipkFormattedTextFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lakiRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(perempuanRadioButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(181, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nikText)
                            .addComponent(namaText)
                            .addComponent(jScrollPane1))
                        .addGap(52, 52, 52))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tidurCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bacaCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(makanCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tgl_lahirFormattedTextField)
                            .addComponent(no_telpTextField)
                            .addComponent(pendidikanComboBox, 0, 190, Short.MAX_VALUE)
                            .addComponent(ipkFormattedTextField))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(daftarButton)
                .addGap(248, 248, 248))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nikText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lakiRadioButton)
                        .addComponent(perempuanRadioButton)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(tidurCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(makanCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bacaCheckBox)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(no_telpTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tgl_lahirFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(pendidikanComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(ipkFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(daftarButton)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tidurCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidurCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidurCheckBoxActionPerformed

    private void daftarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarButtonActionPerformed
        // Validasi semua field terisi
    if (nikText.getText().trim().isEmpty() ||
        namaText.getText().trim().isEmpty() ||
        alamatText.getText().trim().isEmpty() ||
        no_telpTextField.getText().trim().isEmpty() ||
        tgl_lahirFormattedTextField.getText().trim().isEmpty() ||
        ipkFormattedTextField.getText().trim().isEmpty() ||
        pendidikanComboBox.getSelectedIndex() == -1 ||
        (!tidurCheckBox.isSelected() && !makanCheckBox.isSelected() && !bacaCheckBox.isSelected())) {
        
        JOptionPane.showMessageDialog(this,
            "Semua field harus diisi!",
            "Error",
            JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // Validasi pendidikan
    String pendidikanTerpilih = (String) pendidikanComboBox.getSelectedItem();
    if (pendidikanTerpilih.equals("SD") || 
        pendidikanTerpilih.equals("SMP") || 
        pendidikanTerpilih.equals("SMA")) {
        JOptionPane.showMessageDialog(this,
            "Pendidikan minimal D1!",
            "Error",
            JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    
    // Jika semua validasi berhasil
    JOptionPane.showMessageDialog(this,
        "Anda berhasil mendaftar",
        "Sukses",
        JOptionPane.INFORMATION_MESSAGE);
        
    // Reset form
    resetForm();
}

// Tambahkan metode resetForm()
private void resetForm() {
    nikText.setText("");
    namaText.setText("");
    alamatText.setText("");
    genderGroup.clearSelection();
    tidurCheckBox.setSelected(false);
    makanCheckBox.setSelected(false);
    bacaCheckBox.setSelected(false);
    no_telpTextField.setText("");
    tgl_lahirFormattedTextField.setText("");
    pendidikanComboBox.setSelectedIndex(-1);
    ipkFormattedTextField.setText("");
    }//GEN-LAST:event_daftarButtonActionPerformed

    private void makanCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makanCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_makanCheckBoxActionPerformed

    private void bacaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bacaCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bacaCheckBoxActionPerformed

    private void lakiRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakiRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lakiRadioButtonActionPerformed

    private void nikTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nikTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nikTextActionPerformed

    private void namaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaTextActionPerformed

    private void no_telpTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_no_telpTextFieldKeyReleased
        String text = no_telpTextField.getText();
    if (!text.matches("\\d*")) {
        no_telpTextField.setText(text.replaceAll("[^\\d]", ""));
    }
    }//GEN-LAST:event_no_telpTextFieldKeyReleased

    private void no_telpTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_telpTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_telpTextFieldActionPerformed

    private void tgl_lahirFormattedTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tgl_lahirFormattedTextFieldKeyTyped
        // TODO add your handling code here:
      
    }//GEN-LAST:event_tgl_lahirFormattedTextFieldKeyTyped

    private void ipkFormattedTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ipkFormattedTextFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_ipkFormattedTextFieldKeyReleased

    private void pendidikanComboBoxKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pendidikanComboBoxKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_pendidikanComboBoxKeyTyped

    private void tgl_lahirFormattedTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tgl_lahirFormattedTextFieldFocusLost
        // TODO add your handling code here:
        try {
            // Format tanggal lahir yang dimasukkan (misalnya "dd/MM/yyyy")
            String tanggalLahir = tgl_lahirFormattedTextField.getText();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate tanggalLahirDate = LocalDate.parse(tanggalLahir, formatter);

            // Mendapatkan tanggal hari ini
            LocalDate today = LocalDate.now();

            // Menghitung selisih umur dalam tahun
            long usia = ChronoUnit.YEARS.between(tanggalLahirDate, today);

            if (usia < 18) {
                // Jika usia kurang dari 18 tahun, tampilkan peringatan
                JOptionPane.showMessageDialog(this, "Anda belum cukup umur untuk melamar pekerjaan ini", "Peringatan", JOptionPane.WARNING_MESSAGE);
                // Tidak melanjutkan untuk mengisi form
            } 
        } catch (Exception e) {
            // Tangani jika format tanggal salah
            JOptionPane.showMessageDialog(this, "Format tanggal salah. Harap masukkan tanggal dengan format dd/MM/yyyy", "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_tgl_lahirFormattedTextFieldFocusLost

    private void ipkFormattedTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ipkFormattedTextFieldFocusLost
        // TODO add your handling code here:
         try {
        double ipk = Double.parseDouble(ipkFormattedTextField.getText());
        if (ipk < 3.01) {
            JOptionPane.showMessageDialog(this,
                "IPK minimal 3.01!",
                "Error",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
    } catch (NumberFormatException ex) {
        JOptionPane.showMessageDialog(this,
            "IPK tidak valid!",
            "Error",
            JOptionPane.ERROR_MESSAGE);
        return;
    }
    }//GEN-LAST:event_ipkFormattedTextFieldFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BiodataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BiodataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BiodataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BiodataFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BiodataFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane alamatText;
    private javax.swing.JCheckBox bacaCheckBox;
    private javax.swing.JButton daftarButton;
    private javax.swing.ButtonGroup genderGroup;
    private javax.swing.JFormattedTextField ipkFormattedTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton lakiRadioButton;
    private javax.swing.JCheckBox makanCheckBox;
    private javax.swing.JTextField namaText;
    private javax.swing.JTextField nikText;
    private javax.swing.JTextField no_telpTextField;
    private javax.swing.JComboBox<String> pendidikanComboBox;
    private javax.swing.JRadioButton perempuanRadioButton;
    private javax.swing.JFormattedTextField tgl_lahirFormattedTextField;
    private javax.swing.JCheckBox tidurCheckBox;
    // End of variables declaration//GEN-END:variables
 
}
